version: "3.9"

services:
  backend: # Node.js 
    image: node:18-alpine
    container_name: astrostreet_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:PASSWORD123@db:5432/astrostreet
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend: # React for mobile UI
    image: node:18-alpine
    container_name: astrostreet_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # postgreSQL Database for storing player data
  db: 
    image: postgres:15
    container_name: astrostreet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD123
      POSTGRES_DB: astrostreet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
